### ISSUE TITLE
Feature: Add botman install command

### ISSUE THREAD

**Issue by minthemiddle** [christophrumpel/laravel-quiz-chatbot#2]
Great tutorial.
You might make it even more accessible for newbies, though.
You start with `botman new laravelquiz-chatbot`, but people may not have install `botman` yet.
You might add the following:

1. [Install composer](https://getcomposer.org/doc/00-intro.md)
2. Install botman installer via `composer global require "botman/installer"`

**Comment by christophrumpel** [comment]
Hey @minthemiddle , thanks for the nice words.
Yeah, you are right. I have written so often about it that I forget that 🙈
Just added it 👍
