### ISSUE TITLE
Illegal string offset message_id?

### ISSUE THREAD

**Issue by pascalchristian** [christophrumpel/laravel-quiz-chatbot#7]
Hi, I cloned the project into a debian buster lamp stack, and set up the .env and seeded the questions/answers database.

I am unable to start the quiz, with botman throwing illegal string offset error:

   ErrorException  : Illegal string offset 'message_id'

  at /home/bitnami/laravel-quiz-chatbot/app/Http/Middleware/PreventDoubleClicks.php:27
    23|      */
    24|     public function captured(IncomingMessage $message, $next, BotMan $bot)
    25|     {
    26|         // Check if message is a double click
  > 27|         $messageId = $message->getPayload()['message_id'];
    28|         $identifier = 'already_send_message_'.$messageId.'_'.$message->getConversationIdentifier();
    29| 
    30|         if(Cache::has($identifier)) {
    31|             info('message is a duplicate');

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Illegal string offset 'message_id'", "/home/bitnami/laravel-quiz-chatbot/app/Http/Middleware/PreventDoubleClicks.php", [Object(BotMan\BotMan\Messages\Incoming\IncomingMessage), Object(Closure), Object(BotMan\BotMan\BotMan)])
      /home/bitnami/laravel-quiz-chatbot/app/Http/Middleware/PreventDoubleClicks.php:27

  2   App\Http\Middleware\PreventDoubleClicks::captured(Object(BotMan\BotMan\Messages\Incoming\IncomingMessage), Object(Closure), Object(BotMan\BotMan\BotMan))
      /home/bitnami/laravel-quiz-chatbot/vendor/mpociot/pipeline/src/Pipeline.php:151

  Please use the argument -v to see more details.

**Comment by christophrumpel** [comment]
Hey,

this project is already a bit older and I'm not sure if it is still working like that.

Have you tried if just Botman with a basic example is working on your machine?

**Comment by pascalchristian** [comment]
I see. Fresh botman installation works fine on the machine.
